---
- name: Create WeeWX data directory
  ansible.builtin.file:
    path: "{{ weewx_volume }}"
    state: directory
    owner: "1000"
    group: "1000"
    mode: '0755'
  become: true

- name: Deploy WeeWX container
  community.docker.docker_container:
    name: weewx
    image: "felddy/weewx:{{ weewx_image_tag }}"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "{{ docker_network }}"
    volumes:
      - "{{ weewx_volume }}:/data"
    env:
      WEEWX_STATION_TYPE: "Simulator"
      WEEWX_LATITUDE: "{{ weewx_latitude | string }}"
      WEEWX_LONGITUDE: "{{ weewx_longitude | string }}"
      WEEWX_ALTITUDE: "{{ weewx_altitude | string }}, meter"
      WEEWX_LOCATION: "{{ weewx_station_name }}"
      TZ: "{{ rvtc_timezone }}"
