# telegraf_generator.conf — RVTC Generator MQTT → InfluxDB

[[inputs.mqtt_consumer]]
  name_override = "generator"
  servers       = ["tcp://192.168.88.3:1883"]
  topics        = ["rvtc/sensors/generator/#"]
  data_format   = "value"
  data_type     = "float"

[[outputs.influxdb_v2]]
  urls         = ["http://192.168.88.3:8086"]
  token        = "rk98fhNg1QJ4_ox9tpiuI9Qi1Qh_tyUfITOis_Jz99xsDMlM_Q1ljfHPQZOKkR5VpFqi5qfMyJuMvULH8p714A=="
  organization = "rvtc"
  bucket       = "rvtc"