---
- name: Deploy rtl_433 container
  community.docker.docker_container:
    name: rtl433
    image: hertzg/rtl_433:latest
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "{{ docker_network }}"
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    command: >
      -F "mqtt://mosquitto:1883,retain=1"
      -R 40
      -M time:iso
      -M protocol
      -C si
