[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit LSM303DLHC
    adafruit/Adafruit L3GD20 U
    adafruit/Adafruit BMP085 Unified
    adafruit/Adafruit 10DOF
    olikraus/U8g2@^2.35.19
    https://github.com/yaacov/ArduinoModbusSlave.git
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.4
